/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.builder.SpringApplicationBuilder;
@SpringBootApplication
public class Application {
    public static void main(String[] args) {

        new SpringApplicationBuilder(Application.class)
                .application()
                .run(args);
    }
}
