name: CI Pipeline with Allure Reports

on:
  workflow_dispatch:
    inputs:
      exampleInput:
        description: 'Run tests'
        required: false
        default: 'default value'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}

      # Run the Gradle build and execute the tests
      - name: Run tests
        run: ./gradlew clean test

      # Install Allure CLI
     # Download and Install Allure CLI
      - name: Install Allure CLI
        run: |
          curl -o allure-2.21.0.tgz -L https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.21.0/allure-commandline-2.21.0.tgz
          tar -zxvf allure-2.21.0.tgz
          sudo mv allure-2.21.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
          allure --version  # To check if Allure is installed properly

      # Generate Allure Report
      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
        
      # Add reports to summary
      - name: Add reports to summary
        if: contains(fromJSON('["success", "failure"]'), steps.test.outcome) && always()
        run: |
          echo "# Test Reports" >> $GITHUB_STEP_SUMMARY
          echo "[Allure Test Report](https://thivyae.github.io/sample-test-project/test-reports/${{ github.sha }}/${{ github.run_id }}/${{ github.run_attempt }}/allure-report/index.html)" >> $GITHUB_STEP_SUMMARY
          echo "[Tests Report](https://thivyae.github.io/sample-test-project/test-reports/${{ github.sha }}/${{ github.run_id }}/${{ github.run_attempt }}/tests/test/index.html)" >> $GITHUB_STEP_SUMMARY
